[[redirects]]
  from = "/api/*"
  to = "https://smileystocks.onrender.com"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  #headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "POST"}
